version: '3.8'

services:
  app:
    build: .
    image: scientific-evaluation-ui:latest
    ports:
      - "3007:3007"

    # Optional: Set restart policy for production
    restart: unless-stopped

# Optional: Define named volume for persistent uploads (instead of host mount)
volumes:
  uploads_data:
